#!/bin/sh
ssh ubuntu@ec2-3-108-254-35.ap-south-1.compute.amazonaws.com -T <<EOF
    cd ~/learn-jenkins-nodejs
    git pull origin master
    curl -o-  https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v14.18.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF